version: '1'

# create namespaces
namespaces:
  - ns1
  - ns2
  - netnsbr0

# veth pair connection
vethpairs:
  - veth_a:
      name: veth0a
      namespace: ns1
      address: 10.0.0.1/24
    veth_b:
      name: veth0b
      namespace: netnsbr0
  - veth_a:
      name: veth1a
      namespace: ns2
      address: 10.0.0.2/24
    veth_b:
      name: veth1b
      namespace: netnsbr0

bridges:
  - namespace: netnsbr0
    name: br0
    ports:
      - name: veth0b
      - name: veth1b

# costom commands
commands:
  - command: "ping -c 3 10.0.0.2"
    namespace: ns1
  - command: "ip link show"
    namespace: netnsbr0

