version: '1'
namespaces:
  - name: ns1
  - name: ns2
  - name: netnsbr0

networks:
  net1:
    interfaces:
      - name: veth0a
        namespace: ns1
        address: 10.0.0.1/24
      - name: veth0b
        namespace: netnsbr0
  net2:
    interfaces:
      - name: veth1a
        namespace: ns2
        address: 10.0.0.2/24
      - name: veth1b
        namespace: netnsbr0

bridges:
  - namespace: netnsbr0
    name: br0
    interfaces:
      - name: veth0b
      - name: veth1b

tests:
  - type: ping
    from: ns1
    to: 10.0.0.2
    count: 3
