version: '1'
namespaces:
  - name: ns1
  - name: ns2

networks:
  net1:
    interfaces:
      - name: veth0a
        namespace: ns1
        address: 10.0.0.1/24
      - name: veth0b
        namespace: ns2
        address: 10.0.0.2/24

tests:
  - type: ping
    from: ns1
    to: 10.0.0.2
    count: 3
