version: '1'

# create namespaces
namespaces:
  - ns1
  - ns2
  - ns3

# veth pair connection
vethpairs:
  - veth_a:
      name: veth0a
      namespace: ns1
      address: 10.0.0.1/24
    veth_b:
      name: veth0b
      namespace: ns2
      address: 10.0.0.2/24
  - veth_a:
      name: veth1a
      namespace: ns2
      address: 10.0.1.1/24
    veth_b:
      name: veth1b
      namespace: ns3
      address: 10.0.1.2/24

# routing
routes:
  - namespace: ns1
    destination: default
    via: 10.0.0.2
    interface: veth0a
  - namespace: ns3
    destination: default
    via: 10.0.1.1
    interface: veth1b

# costom commands
commands:
  - command: "ping -c 3 10.0.1.2"
    namespace: ns1
  - command: "ping -c 3 10.0.0.1"
    namespace: ns3
  - command: "echo hello network namespase"
  - command: "date +%T"

